### ISSUE TITLE
Nested layouts

### ISSUE THREAD

**Issue by rstacruz** [superwolff/metalsmith-layouts#10]
It would be nice to be able to do nested layouts, just like jekyll. This is probably a long-shot given layouts are not parsed by Metalsmith, but hey, why not.

```yaml
# src/index.html
---
layout: default.html
title: Home page
---
```

```html
<!-- layouts/default.html -->
---
layout: html5.html
body_class: 'default'
---
<div class='menu'>...</div>
<div class='content'>{{{ contents }}}</div>
```

```html
<!-- layouts/html5.html -->
<!doctype html>
<html>
  <meta charset='utf-8'>
  <title>{{ title }}</title>
  <body class='{{ body_class }}'>
  {{{ contents }}}
  </body>
</html>
```
